// Code generated by kubernetes-logs/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:kubernetes-logs` or
// `go generate ./kubernetes-logs/...`.
const uiChecksum = "59141d052721b8b39d99e60095813bd8de426afcd880fe144a40448db501b7ed"
