// Code generated by kubernetes-logs/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:kubernetes-logs` or
// `go generate ./kubernetes-logs/...`.
const uiChecksum = "555ef866ba5c20fc98e405708f14133e6ef5de29fc7f24e7f8aa612fd7559d24"
