// Code generated by kubernetes-logs/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:kubernetes-logs` or
// `go generate ./kubernetes-logs/...`.
const uiChecksum = "af8244f78e36d748acfe732ba1a6c8b352d646e0bdbdf0106dd8b1afde4b6fe0"
