// Code generated by plugins/arthas/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:arthas` or
// `go generate ./plugins/arthas/...`.
const uiChecksum = "371c753ebb8ac1c14068752a03b33e3bed71fa39043101c4cddbcf3ef754bc27"
