// Code generated by plugins/arthas/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:arthas` or
// `go generate ./plugins/arthas/...`.
const uiChecksum = "aa3de343da8b23fc4b8d49b7bf5aeebc591ed3a53539889db0bb1c68c0592666"
