---
apiVersion: mission-control.flanksource.com/v1
kind: Plugin
metadata:
  name: sql-server
  namespace: defatul
spec:
  source: sql-server-mc-plugin
  selector:
    types:
      - MissionControl::Connection
    labelSelector: mission-control/connection-type=mssql
---
apiVersion: mission-control.flanksource.com/v1
kind: Permission
metadata:
  name: allow-sql-server-plugin-connection-read
  namespace: defatul
spec:
  description: allow sql-server plugin to read mission-control database connection.
  subject:
    plugin: defatul/sql-server
  actions:
    - read
  object:
    connections:
      - types:
          - 'sql_server'
