// Code generated by plugins/sql-server/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:sql-server` or
// `go generate ./plugins/sql-server/...`.
const uiChecksum = "fc36eb63f687116bf345926fcadd4d558940e1df42ed16ebb1952f939632eef0"
