// Code generated by plugins/sql-server/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:sql-server` or
// `go generate ./plugins/sql-server/...`.
const uiChecksum = "6dfc9bdfcda594e7424e968bf428b110126ab10ef9473dedc2749c61bfda1a49"
