apiVersion: mission-control.flanksource.com/v1
kind: Plugin
metadata:
  name: postgres
  namespace: mc
spec:
  source: postgres
  selector:
    types:
      - MissionControl::Connection
      - PostgreSQL::Server
      - PostgreSQL::Database
  connections:
    types:
      sql: connection://mc/mission-control
