// Code generated by plugins/postgres/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:postgres` or
// `go generate ./plugins/postgres/...`.
const uiChecksum = "3d97135ed5ec83b76cadf2cdc2761e45a537b1cdeb760715aa091b01a4a16f79"
