name: Build Plugins

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.plugin }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin:
          - arthas
          - golang
          - inspektor-gadget
          - kubernetes-logs
          - postgres
          - sql-server

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ${{ matrix.plugin }}/go.mod
          cache-dependency-path: ${{ matrix.plugin }}/go.sum

      - name: Build
        working-directory: ${{ matrix.plugin }}
        run: go build ./...
